version: '3'

services:
  mongodb:
    container_name: mongodb-task
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data-volume:/data/db
    restart: always
    networks:
      - awesome

  # app:
  #   container_name: app
  #   build:
  #     context: .
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mongodb
  #   restart: always
  #   networks:
  #     - awesome

volumes:
  data-volume:

networks:
  awesome:
    driver: bridge
